ClassPathScanner is more robust now. It ignores "NoClassDefFoundErrors" that may occur if dependent classes are not on classpath. Bumped also avaje-classpath-scanner-api to 2.2-SNAPSHOT so that tests will pass on Windows-machine